### ISSUE TITLE
Count all doses instead of only first doses

### ISSUE THREAD

**Issue by fxedel** [Schedulaar/impf-bot#1]
The column `dosen_erst_differenz_zum_vortag` only counts first vaccinations. This may be a good measure for the number of new vaccinated people, but not for the speed of the whole vaccination campaign. Second vaccinations, which bring the full protection, aren't counted in the impfidenz. At the moment, for example, most vaccinations are second ones, so the impfidenz is relatively low. This could be misunderstood as a signal of slowness in vaccinations centers.

I'd propose using the column `dosen_differenz_zum_vortag` instead. It better communicates how fast the vaccination campaign is going.

**Comment by michael-markl** [comment]
Hello fxedel! Thank you for your feedback! I think you have a point!
As it is most interesting to me, how many "new" people get vaccinated every day  (i.e. the first time) I'd also keep the count for the first vaccinations.
Nevertheless, I will add another number that keeps track of the total count of vaccinations.

**Comment by michael-markl** [comment]
I added a commit https://github.com/Schedulaar/impf-bot/commit/8dc872cb1e9d31fd6c4569c4bd89c71c0864bd47 to address your request. I hope this suits both our needs now.
Feel free to comment if this is not the case or otherwise please close this issue :)

**Comment by fxedel** [comment]
Looks good, thanks! I'll wait for the next update on monday and then I'll close this issue.

**Comment by fxedel** [comment]
Works great :tada:
